#!/usr/bin/env python3
"""
pulisci: find and remove executable files (cleanup binaries, keep source files only).
"""
import sys
import os

usage_string = "pulisci <cartella>"


def main():
    """ main function """
    if len(sys.argv) != 2:
        print(usage_string)
        sys.exit(-1)

    for filename in os.listdir(sys.argv[1]):
        executable = os.access(filename, os.X_OK)
        if (executable):
            print("rm " + filename)
            os.remove(filename)


if __name__ == '__main__':
    main()

